common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    do_mee_ptee: False
    do_mee_ptee_dcaee: True
    mee_bin: [0,0.01,0.02,0.03,0.04,0.06,0.08,0.10,0.12,0.14,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.4,1.7,2.0,2.4,2.7,2.8,2.9,3.0,3.1,3.2,3.3,3.5,4.0,5.0] # in GeV
    ptee_bin: [0,1,1.5,2,2.5,3,3.5,4,4.5,5,6,8,10] #in GeV
    dcaee_bin: [0,1,2,3,4,5,6,7,8,9,10,12,14,16,18,20] #in sigma
data:
    cutnames:
    - "cutname0_data"
    - "cutname1_data"
mc:
    cutnames:
    - "cutname0_mc"
    - "cutname1_mc"
